version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
      - image: circleci/mongo:4.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run coverage
      - store_artifacts:
          path: coverage
workflows:
  sample:
    jobs:
      - build-and-test
