import express from "express";
import { ArticleController, CommentController } from "../../controllers";
import { multerUploader } from "../../helpers/uploader";
import categoryRoutes from "./category";
import commentsRoutes from "./comments";
const router = express.Router();
router.get("/", ArticleController.getArticles);
router.post("/", multerUploader.single("image"), ArticleController.addArticle);
router.use("/categories", categoryRoutes);
router.use("/comments", commentsRoutes);
router.get("/:id", ArticleController.getArticle);
router.delete("/:id", ArticleController.deleteArticle);
router.patch("/:id", ArticleController.updateArticle);
router.post("/:articleId/comment", CommentController.addComment);
export default router;
