name: Coverage

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node: ["16"]
    name: Node ${{ matrix.node }} test
    steps:
      - uses: actions/checkout@master
      - run: npm ci
      - run: npm run coverage
      - uses: codecov/codecov-action@v2
