name: Coverage

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node: ["16"]
    name: Node ${{ matrix.node }} test
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2
      - run: npm ci
      - run: npm run coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          verbose: true # optional (default = false)
