name: Coverage
on: [push]
jobs:
  coverage:
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2
      - run: npm ci
      - run: npm test
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          verbose: true # optional (default = false)
